import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { useEffect, useState } from "react";

interface IPostType {
  userId: number;
  id: number;
  title: string;
  body: string;
}

interface IHomeProps {
  myName: string;
  posts: IPostType[];
}

export default function Home({ myName, posts }: IHomeProps) {
  // type Name = string
  // const name: Name = "shopnil";
  // type MultiplicationType = (a: number, b: number) => number;
  // const sum = (a: number, b: number): number => {
  //   return a + b;
  // };
  // const subtract: (a: number, b: number) => number = (a, b) => {
  //   return a - b;
  // };

  // const multiplication: MultiplicationType = (a, b) => {
  //   return a * b;
  // };

  // function Hello(a: number, b: number): number {
  //   return 5;
  // }
  // const [isHover, setIsHover] = useState<{ name: number | string }>({
  //   name: 5,
  // });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}

export async function getStaticProps() {
  const url = `https://jsonplaceholder.typicode.com/posts`;
  const response = await fetch(url);
  const postData = await response.json();
  return {
    props: {
      myName: "minhaj",
      posts: postData,
    }, // will be passed to the page component as props
    revalidate: 3600,
  };
}
